version: '3.8'

services:
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_URL: http://minio:9000
    volumes:
      - ./data/minio-persistence:/data
      - ./data/minio-persistence/certs:/certs
      - ./data/minio-persistence/certs:/file-storage

    ports:
      - 9000:9000
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-minio-ex:0.0.1
    container_name: spring-boot-minio-ex
    environment:
      PROJECT_PROFILES: "dev" #dev,prod
      SERVER-PATH: "/api"
      API_DOCS_PATH: "/api-docs"
      SWAGGER_UI_ENABLED: "true"
      SWAGGER_UI_PATH: "/documentation"
      MINIO_URL: "http://minio:9000"
      MINIO_PORT: "9000"
      REMOTE_URL: "192.168.44.76/minio-api"
      MINIO_BUCKET: "file-storage"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MAX_FILE_SIZE: "20MB"
      MAX_REQUEST_SIZE: "20MB"
      FILE-SIZE-THRESHOLD: "2KB"
    ports:
      - 8080:8080
    networks:
      - backend
networks:
    backend:
      driver: bridge